<?php
namespace App\Services;
use App\Models\StudentProfile; use App\Models\Test; use Illuminate\Support\Facades\DB; use RuntimeException;
class StudentTestAccessService {
 public function activeEnrollment(StudentProfile $student): ?object { return DB::table('student_enrollments as se')->leftJoin('packages as p','p.id','=','se.package_id')->where('se.student_profile_id',$student->id)->where('se.status','active')->where(fn($q)=>$q->whereNull('se.starts_at')->orWhere('se.starts_at','<=',now()))->where(fn($q)=>$q->whereNull('se.expires_at')->orWhere('se.expires_at','>=',now()))->orderByDesc('se.id')->select('se.*','p.name as package_name','p.exam_id as package_exam_id')->first(); }
 public function selectedTestIds(object $e): ?array { if($e->test_limit===null)return null; return DB::table('student_enrollment_tests')->where('student_enrollment_id',$e->id)->where('selected_by_student',true)->orderBy('selected_at')->pluck('test_id')->map(fn($id)=>(int)$id)->all(); }
 public function select(object $e, Test $test): void { if($e->test_limit===null)return; $this->assertEligible($e,$test); DB::transaction(function()use($e,$test){ DB::table('student_enrollments')->where('id',$e->id)->lockForUpdate()->first(); $q=DB::table('student_enrollment_tests')->where('student_enrollment_id',$e->id); if((clone $q)->where('test_id',$test->id)->where('selected_by_student',true)->exists())return; if((clone $q)->where('selected_by_student',true)->count()>=(int)$e->test_limit)throw new RuntimeException('Your test selection limit is complete.'); DB::table('student_enrollment_tests')->updateOrInsert(['student_enrollment_id'=>$e->id,'test_id'=>$test->id],['selected_by_student'=>true,'selected_at'=>now(),'updated_at'=>now(),'created_at'=>now()]); }); }
 public function unselect(object $e, Test $test): void { if(DB::table('test_attempts')->where('student_profile_id',$e->student_profile_id)->where('test_id',$test->id)->exists())throw new RuntimeException('A test cannot be removed after it has been started.'); DB::table('student_enrollment_tests')->where('student_enrollment_id',$e->id)->where('test_id',$test->id)->update(['selected_by_student'=>false,'selected_at'=>null,'updated_at'=>now()]); }
 public function allows(object $e, Test $test): bool { if(!$this->eligible($e,$test))return false; if($e->test_limit===null)return true; return DB::table('student_enrollment_tests')->where('student_enrollment_id',$e->id)->where('test_id',$test->id)->where('selected_by_student',true)->exists(); }
 public function completedIds(object $e): array { $q=DB::table('test_attempts')->where('student_profile_id',$e->student_profile_id)->where('status','evaluated'); if($e->test_limit!==null)$q->whereIn('test_id',DB::table('student_enrollment_tests')->where('student_enrollment_id',$e->id)->where('selected_by_student',true)->select('test_id')); elseif($e->package_exam_id)$q->whereIn('test_id',DB::table('tests')->where('exam_id',$e->package_exam_id)->select('id')); return $q->distinct()->pluck('test_id')->map(fn($id)=>(int)$id)->all(); }
 public function attemptedIds(object $e): array { return DB::table('test_attempts')->where('student_profile_id',$e->student_profile_id)->distinct()->pluck('test_id')->map(fn($id)=>(int)$id)->all(); }
 public function syncUsage(object $e): void { DB::table('student_enrollments')->where('id',$e->id)->update(['tests_used'=>count($this->completedIds($e)),'updated_at'=>now()]); }
 private function assertEligible(object $e,Test $test):void { if(!$this->eligible($e,$test))throw new RuntimeException('This test is not eligible for your package.'); }
 private function eligible(object $e,Test $test):bool { return $test->is_active&&(!$e->package_exam_id||(int)$test->exam_id===(int)$e->package_exam_id); }
}
