<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account Recovery · {{ config('app.name') }}</title><style>body{font:16px Arial,sans-serif;background:#eef3f8;color:#172b4d;margin:0}main{max-width:520px;margin:40px auto;background:#fff;padding:28px;border-radius:16px;box-shadow:0 8px 30px #17304b18}label{display:block;margin:18px 0 6px}input,select,button{box-sizing:border-box;width:100%;padding:12px;font:inherit;border:1px solid #bac8d8;border-radius:8px}button{background:#164e85;color:white;margin-top:20px;cursor:pointer}.notice{padding:12px;background:#e8f5ed;overflow-wrap:anywhere}.error{background:#fff0ed;padding:12px}a{color:#164e85}h1{font-size:26px}@media(max-width:600px){main{margin:18px 12px;padding:22px}}</style></head><body><main><p>{{ config('app.name') }} · MCI Educational Group</p><h1>Account Recovery</h1><p>पासवर्ड या लॉगिन ईमेल/ID भूल गए?</p>
@if(session('status'))<p class="notice" role="status">{{ session('status') }}</p>@endif
@if($errors->any())<p class="error" role="alert">{{ $errors->first() }}</p>@endif
@foreach(session('recovered_identifiers',[]) as $identifier)<p class="notice">{{ $identifier }}</p>@endforeach
<form method="post" action="{{ route('mci.recovery.send') }}">@csrf
<label for="purpose">What do you need?</label><select id="purpose" name="purpose"><option value="password">Forgot Password / पासवर्ड भूल गए</option><option value="identifier">Forgot Login Email / लॉगिन ईमेल भूल गए</option>@if($applicationPortal)<option value="application">Forgot Student Application Number</option>@endif</select>
<label for="email">Registered email / verified recovery email</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254">
<p>For a password or Application Number, use your registered email. For a forgotten login email, use the separate recovery email you verified earlier.</p><button>Send Email OTP</button></form>
@if(session('mci_recovery_pending'))<hr><form method="post" action="{{ route('mci.recovery.verify') }}">@csrf<label for="code">Email OTP</label><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required>
@if(session('mci_recovery_pending.purpose')==='password')<label for="password">New password</label><input id="password" name="password" type="password" autocomplete="new-password" minlength="12" required><label for="password_confirmation">Confirm new password</label><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" minlength="12" required><p>Use at least 12 characters with uppercase, lowercase, number and symbol.</p>@endif<button>Verify and Continue</button></form>@endif
<p>If no recovery email was enrolled and you cannot access your registered email, contact the institution for identity verification.</p><p><a href="/">← Back to website</a></p></main></body></html>
