@extends('library-practice.layout')
@section('title', '10 मुफ्त मासिक टेस्ट')
@section('content')
<div class="card"><h1>ऑनलाइन प्रैक्टिस सेट</h1><p>{{ $account->student_name }} · {{ $account->student_code }} · महीना {{ $month->period }}</p><p><strong>₹0 · हर महीने 10 पूरे टेस्ट सेट</strong></p></div>
<div class="grid"><div class="card"><div class="muted">मासिक सीमा</div><div class="metric">10</div></div><div class="card"><div class="muted">चुने हुए सेट</div><div class="metric">{{ $selections->count() }}</div></div><div class="card"><div class="muted">पूरे किए</div><div class="metric">{{ $completed }}</div></div><div class="card"><div class="muted">और चुन सकते हैं</div><div class="metric">{{ max(0,10-$selections->count()) }}</div></div></div>
@unless($eligible)<div class="card error">सदस्यता अभी सक्रिय नहीं है। नए मुफ्त सेट लेने के लिए लाइब्रेरी कार्यालय से सदस्यता और फीस अपडेट कराएँ। आपके पुराने परिणाम नीचे उपलब्ध हैं।</div>@endunless
<details class="card"><summary><strong>मासिक सुविधा की शर्तें</strong></summary><ol><li>सक्रिय लाइब्रेरी विद्यार्थियों को हर कैलेंडर महीने 10 सेट मुफ्त। अतिरिक्त शुल्क ₹0।</li><li>हर महीने की 1 तारीख को नई सीमा मिलेगी। बचे सेट अगले महीने नहीं जुड़ेंगे।</li><li>टेस्ट शुरू करने से पहले चयन बदल सकते हैं; शुरू किया हुआ सेट सीमा में गिना रहेगा।</li><li>प्रश्नों की संख्या, समय, अंक और नेगेटिव मार्किंग नीचे प्रत्येक टेस्ट में दिए हैं। उत्तर कुंजी उसी टेस्ट के एडमिन नियम के अनुसार खुलेगी।</li><li>सदस्यता बंद होने पर नए टेस्ट नहीं मिलेंगे। पहले शुरू किया हुआ प्रयास पूरा कर सकते हैं और पुराने परिणाम देख सकते हैं।</li></ol></details>
<h2>इस महीने मेरे चुने हुए सेट</h2><div class="tests">
@forelse($selectedTests as $test)
@php($selection=$selections->get($test->id))
<article class="card test"><h3>{{ $test->title }}</h3><p class="muted">Set #{{ $test->id }} · {{ ucwords(str_replace('_', ' ', $test->test_type)) }}</p><p class="muted">{{ $test->exam?->name }} · {{ $test->duration_minutes }} मिनट · {{ $test->total_questions }} प्रश्न</p><div class="actions">
@if($selection->test_attempt_id)<a class="btn" href="{{ route('library-practice.attempts.show',$selection->test_attempt_id) }}">प्रयास / परिणाम खोलें</a>
@elseif($eligible)<form method="POST" action="{{ route('library-practice.start',$test) }}">@csrf<button>टेस्ट शुरू करें</button></form>@endif
@unless($selection->test_attempt_id)<form method="POST" action="{{ route('library-practice.unselect',$test) }}">@csrf @method('DELETE')<button class="btn alt">चयन बदलें / हटाएँ</button></form>@endunless
</div></article>
@empty<div class="card">नीचे सूची से अपने टेस्ट सेट चुनें।</div>@endforelse</div>
<section class="card"><h2>श्रेणी के अनुसार टेस्ट चुनें</h2>@include('layouts.test-catalog-filters', ['catalogRoute' => route('library-practice.index')])</section>
<div class="tests">@forelse($tests as $test)<article class="card test"><h3>{{ $test->title }}</h3><p class="muted">Set #{{ $test->id }} · {{ ucwords(str_replace('_', ' ', $test->test_type)) }}</p><p class="muted">{{ $test->exam?->category?->name }} · {{ $test->exam?->name }}</p><p>{{ $test->duration_minutes }} मिनट · {{ $test->total_questions }} प्रश्न · सही उत्तर +{{ $test->positive_marks }} · गलत उत्तर −{{ $test->negative_marks }}</p>@if($test->instructions)<details><summary>टेस्ट के निर्देश</summary><p>{!! nl2br(e($test->instructions)) !!}</p></details>@endif<div class="actions">@if($selections->has($test->id))<strong>आपके मासिक सेट में चुना हुआ</strong>@elseif($eligible && $selections->count()<10)<form method="POST" action="{{ route('library-practice.select',$test) }}">@csrf<button>मुफ्त सेट में चुनें</button></form>@else<span class="muted">{{ $eligible?'इस महीने की चयन सीमा पूरी है।':'सक्रिय सदस्यता आवश्यक है।' }}</span>@endif</div></article>@empty<div class="card">इस फ़िल्टर में उपलब्ध टेस्ट नहीं मिले।</div>@endforelse</div>{{ $tests->links() }}
<section class="card"><h2>मेरे प्रयास और पुराने परिणाम</h2><div class="tableWrap"><table><thead><tr><th>टेस्ट</th><th>तारीख</th><th>स्थिति</th><th>खोलें</th></tr></thead><tbody>@forelse($attempts as $attempt)<tr><td>{{ $attempt->test->title }}</td><td>{{ $attempt->started_at?->format('d M Y') }}</td><td>{{ $attempt->status==='evaluated'?'पूरा हुआ':'शुरू किया हुआ' }}</td><td><a href="{{ route('library-practice.attempts.show',$attempt) }}">प्रयास / परिणाम</a></td></tr>@empty<tr><td colspan="4">अभी कोई प्रयास नहीं है।</td></tr>@endforelse</tbody></table></div>{{ $attempts->links() }}</section>
@endsection
